services:
  inference-worker:
    image: ${ECR_REGISTRY_URL}:latest
    restart: always
    environment:
      - III_URL=${III_URL}
    volumes:
      - ./workers/inference-worker/inference_worker.py:/app/inference_worker.py
