server {
    listen 80;
    
    location /api/ { proxy_pass http://engine:3111/; }
    location /ws {
        proxy_pass http://engine:49134/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /stream/ {
        proxy_pass http://engine:3112;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location / { proxy_pass http://engine:3111; }
}
